package me.altered.platformer.glfw.input

import me.altered.platformer.glfw.IntEnum
import org.lwjgl.glfw.GLFW.*

enum class Cursor(override val code: Int) : IntEnum {

    ARROW(GLFW_ARROW_CURSOR),
    IBEAM(GLFW_IBEAM_CURSOR),
    CROSSHAIR(GLFW_CROSSHAIR_CURSOR),
    POINTING_HAND(GLFW_POINTING_HAND_CURSOR),
    RESIZE_EW(GLFW_RESIZE_EW_CURSOR),
    RESIZE_NS(GLFW_RESIZE_NS_CURSOR),
    RESIZE_NWSE(GLFW_RESIZE_NWSE_CURSOR),
    RESIZE_NESW(GLFW_RESIZE_NESW_CURSOR),
    RESIZE_ALL(GLFW_RESIZE_ALL_CURSOR),
    NOT_ALLOWED(GLFW_NOT_ALLOWED_CURSOR),
}
