package me.altered.platformer.engine.input

import me.altered.platformer.engine.util.IntEnum
import java.awt.event.KeyEvent.*

@Suppress("unused")
actual enum class Key(override val code: Int) : IntEnum {
    Unknown(VK_UNDEFINED),
    Space(VK_SPACE),
    Apostrophe(0), // FIXME: find code
    Comma(VK_COMMA),
    Minus(VK_MINUS),
    Period(VK_PERIOD),
    Slash(VK_SLASH),
    N0(VK_0),
    N1(VK_1),
    N2(VK_2),
    N3(VK_3),
    N4(VK_4),
    N5(VK_5),
    N6(VK_6),
    N7(VK_7),
    N8(VK_8),
    N9(VK_9),
    Semicolon(VK_SEMICOLON),
    Equal(VK_EQUALS),
    A(VK_A),
    B(VK_B),
    C(VK_C),
    D(VK_D),
    E(VK_E),
    F(VK_F),
    G(VK_G),
    H(VK_H),
    I(VK_I),
    J(VK_J),
    K(VK_K),
    L(VK_L),
    M(VK_M),
    N(VK_N),
    O(VK_O),
    P(VK_P),
    Q(VK_Q),
    R(VK_R),
    S(VK_S),
    T(VK_T),
    U(VK_U),
    V(VK_V),
    W(VK_W),
    X(VK_X),
    Y(VK_Y),
    Z(VK_Z),
    LeftBracket(VK_OPEN_BRACKET),
    Backslash(VK_BACK_SLASH),
    RightBracket(VK_CLOSE_BRACKET),
    GraveAccent(VK_DEAD_GRAVE), // FIXME: may not be right
    World1(0), // FIXME: find code
    World2(0), // FIXME: find code
    Escape(VK_ESCAPE),
    Enter(VK_ENTER),
    Tab(VK_TAB),
    Backspace(VK_BACK_SPACE),
    Insert(VK_INSERT),
    Delete(VK_DELETE),
    Right(VK_RIGHT),
    Left(VK_LEFT),
    Down(VK_DOWN),
    Up(VK_UP),
    PageUp(VK_PAGE_UP),
    PageDown(VK_PAGE_DOWN),
    Home(VK_HOME),
    End(VK_END),
    CapsLock(VK_CAPS_LOCK),
    ScrollLock(VK_SCROLL_LOCK),
    NumLock(VK_NUM_LOCK),
    PrintScreen(VK_PRINTSCREEN),
    Pause(VK_PAUSE),
    F1(VK_F1),
    F2(VK_F2),
    F3(VK_F3),
    F4(VK_F4),
    F5(VK_F5),
    F6(VK_F6),
    F7(VK_F7),
    F8(VK_F8),
    F9(VK_F9),
    F10(VK_F10),
    F11(VK_F11),
    F12(VK_F12),
    F13(VK_F13),
    F14(VK_F14),
    F15(VK_F15),
    F16(VK_F16),
    F17(VK_F17),
    F18(VK_F18),
    F19(VK_F19),
    F20(VK_F20),
    F21(VK_F21),
    F22(VK_F22),
    F23(VK_F23),
    F24(VK_F24),
    KP0(VK_NUMPAD0),
    KP1(VK_NUMPAD1),
    KP2(VK_NUMPAD2),
    KP3(VK_NUMPAD3),
    KP4(VK_NUMPAD4),
    KP5(VK_NUMPAD5),
    KP6(VK_NUMPAD6),
    KP7(VK_NUMPAD7),
    KP8(VK_NUMPAD8),
    KP9(VK_NUMPAD9),
    KPDecimal(VK_DECIMAL),
    KPDivide(VK_DIVIDE),
    KPMultiply(VK_MULTIPLY),
    KPSubtract(VK_SUBTRACT),
    KPAdd(VK_ADD),
    KPEnter(VK_ENTER), // FIXME: no keypad enter???
    KPEqual(VK_EQUALS), // FIXME: no keypad equals???
    Shift(VK_SHIFT),
    Control(VK_CONTROL),
    Alt(VK_ALT),
    Super(VK_WINDOWS),
    Menu(VK_CONTEXT_MENU),
}
