package me.altered.platformer.engine.input

import me.altered.platformer.engine.util.IntEnum
import java.awt.event.KeyEvent.*

@Suppress("unused")
actual enum class Key(override val code: Int) : IntEnum {
    UNKNOWN(VK_UNDEFINED),
    SPACE(VK_SPACE),
    APOSTROPHE(0), // FIXME: find code
    COMMA(VK_COMMA),
    MINUS(VK_MINUS),
    PERIOD(VK_PERIOD),
    SLASH(VK_SLASH),
    N0(VK_0),
    N1(VK_1),
    N2(VK_2),
    N3(VK_3),
    N4(VK_4),
    N5(VK_5),
    N6(VK_6),
    N7(VK_7),
    N8(VK_8),
    N9(VK_9),
    SEMICOLON(VK_SEMICOLON),
    EQUAL(VK_EQUALS),
    A(VK_A),
    B(VK_B),
    C(VK_C),
    D(VK_D),
    E(VK_E),
    F(VK_F),
    G(VK_G),
    H(VK_H),
    I(VK_I),
    J(VK_J),
    K(VK_K),
    L(VK_L),
    M(VK_M),
    N(VK_N),
    O(VK_O),
    P(VK_P),
    Q(VK_Q),
    R(VK_R),
    S(VK_S),
    T(VK_T),
    U(VK_U),
    V(VK_V),
    W(VK_W),
    X(VK_X),
    Y(VK_Y),
    Z(VK_Z),
    LEFT_BRACKET(VK_OPEN_BRACKET),
    BACKSLASH(VK_BACK_SLASH),
    RIGHT_BRACKET(VK_CLOSE_BRACKET),
    GRAVE_ACCENT(VK_DEAD_GRAVE), // FIXME: may not be right
    WORLD_1(0), // FIXME: find code
    WORLD_2(0), // FIXME: find code
    ESCAPE(VK_ESCAPE),
    ENTER(VK_ENTER),
    TAB(VK_TAB),
    BACKSPACE(VK_BACK_SPACE),
    INSERT(VK_INSERT),
    DELETE(VK_DELETE),
    RIGHT(VK_RIGHT),
    LEFT(VK_LEFT),
    DOWN(VK_DOWN),
    UP(VK_UP),
    PAGE_UP(VK_PAGE_UP),
    PAGE_DOWN(VK_PAGE_DOWN),
    HOME(VK_HOME),
    END(VK_END),
    CAPS_LOCK(VK_CAPS_LOCK),
    SCROLL_LOCK(VK_SCROLL_LOCK),
    NUM_LOCK(VK_NUM_LOCK),
    PRINT_SCREEN(VK_PRINTSCREEN),
    PAUSE(VK_PAUSE),
    F1(VK_F1),
    F2(VK_F2),
    F3(VK_F3),
    F4(VK_F4),
    F5(VK_F5),
    F6(VK_F6),
    F7(VK_F7),
    F8(VK_F8),
    F9(VK_F9),
    F10(VK_F10),
    F11(VK_F11),
    F12(VK_F12),
    F13(VK_F13),
    F14(VK_F14),
    F15(VK_F15),
    F16(VK_F16),
    F17(VK_F17),
    F18(VK_F18),
    F19(VK_F19),
    F20(VK_F20),
    F21(VK_F21),
    F22(VK_F22),
    F23(VK_F23),
    F24(VK_F24),
    KP_0(VK_NUMPAD0),
    KP_1(VK_NUMPAD1),
    KP_2(VK_NUMPAD2),
    KP_3(VK_NUMPAD3),
    KP_4(VK_NUMPAD4),
    KP_5(VK_NUMPAD5),
    KP_6(VK_NUMPAD6),
    KP_7(VK_NUMPAD7),
    KP_8(VK_NUMPAD8),
    KP_9(VK_NUMPAD9),
    KP_DECIMAL(VK_DECIMAL),
    KP_DIVIDE(VK_DIVIDE),
    KP_MULTIPLY(VK_MULTIPLY),
    KP_SUBTRACT(VK_SUBTRACT),
    KP_ADD(VK_ADD),
    KP_ENTER(VK_ENTER), // FIXME: no keypad enter???
    KP_EQUAL(VK_EQUALS), // FIXME: no keypad equals???
    SHIFT(VK_SHIFT),
    CONTROL(VK_CONTROL),
    ALT(VK_ALT),
    SUPER(VK_WINDOWS),
    MENU(VK_CONTEXT_MENU),
}
