[versions]
kotlin = "2.0.0-RC2"
skiko = "0.8.4"
coroutines = "1.8.0"

[libraries]
skiko = { group = "org.jetbrains.skiko", name = "skiko", version.ref = "skiko" }

skiko-jvm = { group = "org.jetbrains.skiko", name = "skiko-awt", version.ref = "skiko" }
skiko-jvm-windows = { group = "org.jetbrains.skiko", name = "skiko-awt-runtime-windows-x64", version.ref = "skiko" }
skiko-jvm-linux-x64 = { group = "org.jetbrains.skiko", name = "skiko-awt-runtime-linux-x64", version.ref = "skiko" }
skiko-jvm-linux-arm64 = { group = "org.jetbrains.skiko", name = "skiko-awt-runtime-linux-arm64", version.ref = "skiko" }
skiko-jvm-macos-x64 = { group = "org.jetbrains.skiko", name = "skiko-awt-runtime-macos-x64", version.ref = "skiko" }
skiko-jvm-macos-arm64 = { group = "org.jetbrains.skiko", name = "skiko-awt-runtime-macos-arm64", version.ref = "skiko" }

skiko-ios-x64 = { group = "org.jetbrains.skiko", name = "skiko-iosx64", version.ref = "skiko" }
skiko-ios-arm64 = { group = "org.jetbrains.skiko", name = "skiko-iosarm64", version.ref = "skiko" }
skiko-macos-x64 = { group = "org.jetbrains.skiko", name = "skiko-macosx64", version.ref = "skiko" }
skiko-macos-arm64 = { group = "org.jetbrains.skiko", name = "skiko-macosarm64", version.ref = "skiko" }
skiko-android = { group = "org.jetbrains.skiko", name = "skiko-android", version.ref = "skiko" }
skiko-android-x64 = { group = "org.jetbrains.skiko", name = "skiko-android-runtime-x64", version.ref = "skiko" }
skiko-android-arm64 = { group = "org.jetbrains.skiko", name = "skiko-android-runtime-arm64", version.ref = "skiko" }

kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[bundles]
skiko-jvm = [ "skiko-jvm", "skiko-jvm-windows", "skiko-jvm-linux-x64", "skiko-jvm-linux-arm64", "skiko-jvm-macos-x64", "skiko-jvm-macos-arm64" ]
