[versions]
kotlin = "2.0.0-RC2"
skija = "0.116.2"
lwjgl = "3.3.3"
coroutines = "1.8.0"
joml = "1.10.5"

[libraries]
lwjgl-bom = { group = "org.lwjgl", name = "lwjgl-bom", version.ref = "lwjgl" }
lwjgl = { group = "org.lwjgl", name = "lwjgl" }
lwjgl-glfw = { group = "org.lwjgl", name = "lwjgl-glfw" }
lwjgl-opengl = { group = "org.lwjgl", name = "lwjgl-opengl" }

skija-windows-x64 = { group = "io.github.humbleui", name = "skija-windows-x64", version.ref = "skija" }
skija-linux-x64 = { group = "io.github.humbleui", name = "skija-linux-x64", version.ref = "skija" }
skija-macos-x64 = { group = "io.github.humbleui", name = "skija-macos-x64", version.ref = "skija" }
skija-macos-arm64 = { group = "io.github.humbleui", name = "skija-macos-arm64", version.ref = "skija" }

kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

joml = { group = "org.joml", name = "joml", version.ref = "joml" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[bundles]
lwjgl-withNatives = [ "lwjgl", "lwjgl-glfw", "lwjgl-opengl" ]
skija = [ "skija-windows-x64", "skija-linux-x64", "skija-macos-x64", "skija-macos-arm64" ]
