package me.altered.platformer.glfw

import org.lwjgl.glfw.GLFW.GLFW_ACCUM_ALPHA_BITS
import org.lwjgl.glfw.GLFW.GLFW_ACCUM_BLUE_BITS
import org.lwjgl.glfw.GLFW.GLFW_ACCUM_GREEN_BITS
import org.lwjgl.glfw.GLFW.GLFW_ACCUM_RED_BITS
import org.lwjgl.glfw.GLFW.GLFW_ALPHA_BITS
import org.lwjgl.glfw.GLFW.GLFW_AUX_BUFFERS
import org.lwjgl.glfw.GLFW.GLFW_BLUE_BITS
import org.lwjgl.glfw.GLFW.GLFW_CLIENT_API
import org.lwjgl.glfw.GLFW.GLFW_CONTEXT_ROBUSTNESS
import org.lwjgl.glfw.GLFW.GLFW_CONTEXT_VERSION_MAJOR
import org.lwjgl.glfw.GLFW.GLFW_CONTEXT_VERSION_MINOR
import org.lwjgl.glfw.GLFW.GLFW_DECORATED
import org.lwjgl.glfw.GLFW.GLFW_DEPTH_BITS
import org.lwjgl.glfw.GLFW.GLFW_GREEN_BITS
import org.lwjgl.glfw.GLFW.GLFW_OPENGL_DEBUG_CONTEXT
import org.lwjgl.glfw.GLFW.GLFW_OPENGL_FORWARD_COMPAT
import org.lwjgl.glfw.GLFW.GLFW_OPENGL_PROFILE
import org.lwjgl.glfw.GLFW.GLFW_RED_BITS
import org.lwjgl.glfw.GLFW.GLFW_REFRESH_RATE
import org.lwjgl.glfw.GLFW.GLFW_RESIZABLE
import org.lwjgl.glfw.GLFW.GLFW_SAMPLES
import org.lwjgl.glfw.GLFW.GLFW_SRGB_CAPABLE
import org.lwjgl.glfw.GLFW.GLFW_STENCIL_BITS
import org.lwjgl.glfw.GLFW.GLFW_STEREO
import org.lwjgl.glfw.GLFW.GLFW_VISIBLE

enum class WindowHint(override val code: Int) : IntEnum {
    RESIZABLE(GLFW_RESIZABLE),
    VISIBLE(GLFW_VISIBLE),
    DECORATED(GLFW_DECORATED),
    RED_BITS(GLFW_RED_BITS),
    GREEN_BITS(GLFW_GREEN_BITS),
    BLUE_BITS(GLFW_BLUE_BITS),
    ALPHA_BITS(GLFW_ALPHA_BITS),
    DEPTH_BITS(GLFW_DEPTH_BITS),
    STENCIL_BITS(GLFW_STENCIL_BITS),
    ACCUM_RED_BITS(GLFW_ACCUM_RED_BITS),
    ACCUM_GREEN_BITS(GLFW_ACCUM_GREEN_BITS),
    ACCUM_BLUE_BITS(GLFW_ACCUM_BLUE_BITS),
    ACCUM_ALPHA_BITS(GLFW_ACCUM_ALPHA_BITS),
    AUX_BUFFERS(GLFW_AUX_BUFFERS),
    SAMPLES(GLFW_SAMPLES),
    REFRESH_RATE(GLFW_REFRESH_RATE),
    STEREO(GLFW_STEREO),
    SRGB_CAPABLE(GLFW_SRGB_CAPABLE),
    CLIENT_API(GLFW_CLIENT_API),
    CONTEXT_VERSION_MAJOR(GLFW_CONTEXT_VERSION_MAJOR),
    CONTEXT_VERSION_MINOR(GLFW_CONTEXT_VERSION_MINOR),
    CONTEXT_ROBUSTNESS(GLFW_CONTEXT_ROBUSTNESS),
    OPENGL_FORWARD_COMPAT(GLFW_OPENGL_FORWARD_COMPAT),
    OPENGL_DEBUG_CONTEXT(GLFW_OPENGL_DEBUG_CONTEXT),
    OPENGL_PROFILE(GLFW_OPENGL_PROFILE),
}
